apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
      <body>
        <h1>my beautiful app</h1>
        <b>really</b>
      </body>
    </html>
