apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
      <body>
        <h1>nginx from agent times 2</h1>
      </body>
    </html>
